### ISSUE TITLE
get stuck to enter the password

### ISSUE THREAD

**Issue by tqer** [BosslandGmbH/HBRelog#28]
the log is that:

[11/17/2016 15:36:51] HBRelog Version 1.1.12
[11/17/2016 15:36:51] ******* Settings ******** 
[11/17/2016 15:36:51] 	Auto AcceptTosEula:            False
[11/17/2016 15:36:51] 	Auto Start:                    False
[11/17/2016 15:36:51] 	Auto Update HB:                True
[11/17/2016 15:36:51] 	Check Hb's Responsiveness:     True
[11/17/2016 15:36:51] 	Check Realm Status:            False
[11/17/2016 15:36:51] 	HB Delay:                      3
[11/17/2016 15:36:51] 	Login Delay:                   0
[11/17/2016 15:36:51] 	Store Settings Locally         True
[11/17/2016 15:36:51] 	Set GameWindow Title:          False
[11/17/2016 15:36:51] 	Wow Start Delay:               0
[11/17/2016 15:36:54] 战士: ********* Tasks ***********
[11/17/2016 15:36:54] 战士: ********* End of Task list ***********
[11/17/2016 15:36:54] 战士: Starting D:\WOW\World Of Warcraft\Wow.exe
[11/17/2016 15:36:55] 战士: Waiting for Wow to start
[11/17/2016 15:43:31] 战士: ********* Tasks ***********
[11/17/2016 15:43:31] 战士: ********* End of Task list ***********
[11/17/2016 15:43:31] 战士: Starting D:\WOW\World Of Warcraft\Wow.exe
[11/17/2016 15:43:32] 战士: Waiting for Wow to start
[11/17/2016 15:43:35] System.IO.FileNotFoundException: Could not load file or assembly 'Fasm.NET.dll' or one of its dependencies. 找不到指定的模块。
File name: 'Fasm.NET.dll'
   at GreyMagic.ExternalProcessReader..ctor(Process proc)
   at HighVoltz.HBRelog.WoW.WowLockToken.StartWoW()
   at HighVoltz.HBRelog.WoW.States.StartWowState.Run()
   at HighVoltz.HBRelog.FiniteStateMachine.FiniteStateMachine.Engine.Pulse()
   at HighVoltz.HBRelog.WoW.WowManager.Pulse()
   at HighVoltz.HBRelog.TaskManager.Pulse()
   at HighVoltz.HBRelog.HbRelogManager.DoWork()

can anybody help me?
[Log[2016-11-17_03-36-51].txt](https://github.com/highvoltz/HBRelog/files/596861/Log.2016-11-17_03-36-51.txt)

**Comment by highvoltz** [comment]
Make sure that you have [.Net 4.6.1](https://www.microsoft.com/en-us/download/details.aspx?id=49982) and [visual C++ Redist. for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed on your computur
