### ISSUE TITLE
HB relog is not able to get focus and sometimes ends up spamming hb while there's no wow process running

### ISSUE THREAD

**Issue by shpilim** [BosslandGmbH/HBRelog#30]
I'm using 2 auction accounts. 
Each time i use HBrelog API to switch between realms and characters but it is a nightmare. First it steals mouse and all controll .  Third it stucks in this loop.(stealing controll from other bots).
Could you tell me why you've decided to make some parts to steal focus. Some without it.

**Comment by highvoltz** [comment]
HBRelog needs to focus WoW in order to switch servers, there's no way around it besides using injection.  The WoW servers remember which server you were on last and it uses that server when you start WoW the next time.  The new 1.1.13 release has bigger delays in between mouse clicks, making it easier to break out of the loop if stuck. Have you figured out why it's getting stuck?

**Comment by shpilim** [comment]
1. Since new update it can't find some servers in list
[11:54:09 AM] System.NullReferenceException: Object reference not set to an instance of an object.
   at HighVoltz.HBRelog.WoW.States.RealmSelectState.get_RealmTabs()
   at HighVoltz.HBRelog.WoW.States.RealmSelectState.Run()
   at HighVoltz.HBRelog.FiniteStateMachine.FiniteStateMachine.Engine.Pulse()
   at HighVoltz.HBRelog.WoW.WowManager.Pulse()
   at HighVoltz.HBRelog.TaskManager.Pulse()
   at HighVoltz.HBRelog.CharacterProfile.Pulse()
   at HighVoltz.HBRelog.Settings.GroupSettings.Pulse()
   at HighVoltz.HBRelog.Settings.GroupSettings.Pulse()
   at HighVoltz.HBRelog.HbRelogManager.DoWork()
2. It can't get focus too often even if it's the only wow running in VM. When i help it starts to work
